# Generated by Django 4.0.4 on 2022-09-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('type', models.CharField(default='type', max_length=20)),
                ('isbn', models.CharField(default='ISBN0000', max_length=20)),
                ('author', models.CharField(default='author', max_length=100)),
                ('status', models.CharField(default='status', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='username', max_length=100)),
                ('type', models.CharField(default='student', max_length=20)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('dept', models.CharField(default='dept', max_length=20)),
            ],
        ),
    ]
