# Generated by Django 4.0.4 on 2022-09-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='status',
        ),
        migrations.AddField(
            model_name='book',
            name='books_count',
            field=models.IntegerField(default=10, max_length=100),
        ),
        migrations.AddField(
            model_name='bookuser',
            name='email',
            field=models.CharField(default='username', max_length=100),
        ),
        migrations.AddField(
            model_name='bookuser',
            name='isbn',
            field=models.CharField(default='ISBN0000', max_length=20),
        ),
        migrations.AddField(
            model_name='bookuser',
            name='reserve_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='status',
            field=models.BooleanField(default=True, max_length=20),
        ),
    ]
