# Generated by Django 4.0.4 on 2022-09-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_bookuser_email_bookuser_email_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookuser',
            name='reserve_id',
        ),
    ]
